FROM redalvagui/debian11:latest
COPY entrypoint.sh /
ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=
ENV AWS_DEFAULT_REGION=us-east-1
ENV AWS_DEFAULT_OUTPUT=json
ENV AWS_REPOSITORY=
ENV LATEST=
ENV IMAGE_TAG=
ENTRYPOINT ["/entrypoint.sh"]
