#!/bin/sh

docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST
docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$REPOTAG
docker push $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST
docker push $ECR_REGISTRY/$ECR_REPOSITORY:$REPOTAG
echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$REPOTAG" >> $GITHUB_OUTPUT
echo $ECR_REGISTRY/$ECR_REPOSITORY:$REPOTAG
